title: William Chen 
logo: /IMG_9016.jpg
description: Welcome to my website.  You can find me on [LinkedIn](https://www.linkedin.com/in/william-chen-5456261a9/) or email me at williamchen5667@gmail.com
theme: jekyll-theme-minimal
